### ISSUE TITLE
PHP Fatal error:  Declaration of WP_CLI\Core\CoreUpgrader::download_package($package, $check_signatures = true) must be compatible with WP

### ISSUE THREAD

**Issue by wd7080** [wp-cli/core-command#182]
I run this command to update my WordPress installation to the latest version:

`sudo -u www-data wp core update --version=5.7`

The outcome is:

`PHP Fatal error:  Declaration of WP_CLI\Core\CoreUpgrader::download_package($package, $check_signatures = true) must be compatible with WP_Upgrader::download_package($package, $check_signatures = false, $hook_extra = []) in phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/WP_CLI/Core/CoreUpgrader.php on line 30`

I was able to update the site manually. Any idea why or troubleshooting I have to perform? 
I run LEMP on ubuntu 20.04. My PHP version is 8.0.3.

**Comment by smarek** [comment]
I have reproduced same issue on PHP 7.4.16, so it's not matter of php version compatibility imho

**Comment by smarek** [comment]
@wojsmol seems like the issue is fixed for me, however i'm having trouble reproducing the issue. Even when I downgraded the issue does not appear anymore, i suspect, something is getting cached and maybe the broken/fixed part of code is not triggered always
I've tried `wp-cli cache clear` before testing again with lower version, but that does not seem to have any effect
Could you maybe advise on the testing?
