### ISSUE TITLE
WP-CLI: Installing Subdomain in non-root folder is adding foldername to URL

### ISSUE THREAD

**Issue by Elschnuppero** [wp-cli/core-command#51]
Hi there,

Everytime i try to install wordpress in a regular folder with a subdomain pointing on it, it fails my installation by adding the name of the folder to the URL.

Example: I tried to install a site for testing the new gutenberg-editor on gutenberg.xxx.com. this installation is located on my server in a folder named gutenberg. when the installation finishes the options-table in the db for site-url and home shows me: gutenberg.xxx.com/gutenberg

I installed it with:

`wp core install --url=gutenberg.xxx.com \
--title="Gutenberg Test" \
--admin_user=xxx \
--admin_password=xxx \
--admin_email=xxx`
I also tried

`wp core install --url=gutenberg.xxx.com --title="Gutenberg Test" --admin_name=xxx --admin_password=xxx --admin_email=xxx`

On my local machine (with xampp) everything works fine.

Thanks

**Comment by marksabbath** [comment]
Hi @Elschnuppero 

This is not related to `wp-cli` itself. It's more like the function [wp_guess_url](https://github.com/WordPress/WordPress/blob/aaf99e691391cfceb004d848450dbbf3344b1bee/wp-includes/functions.php#L4472-L4509) of WordPress core.

This function has the responsibility to determine the value of `siteurl`. As you can see in the code, if it doesn't find a constant `WP_SITEURL`, it will try to "guess" this value, by trying to get some attributes of `$_SERVER` (REQUEST_URI, SCRITP_NAME, etc). Since we're in `cli` we don't have a REQUEST_URI which might be causing this issue.

My advice would be including the constant  `WP_SITEURL` into your `wp-config.php`.

Example:

```
$ wp config create --dbname=testing --dbuser=wp --dbpass=securepswd --extra-php <<PHP
$ define( 'WP_SITEURL', 'gutenberg.xxx.com' );
$ PHP
```

**Comment by danielbachhuber** [comment]
See also https://github.com/wp-cli/wp-cli/issues/858 and https://github.com/wp-cli/wp-cli/issues/2168

**Comment by Elschnuppero** [comment]
Hi @marksabbath,
thank you for your solution.

And its working for the frontend of the site, but strangely the backend is now "missing", because its redirecting to http://gutenberg.xxx.com/wp-admin/gutenberg.xxx.com/wp-login.php?redirect_to=http%3A%2F%2Fgutenberg.xxx.com%2Fwp-admin%2F&reauth=1
