### ISSUE TITLE
use same name to describe title and blogname

### ISSUE THREAD

**Issue by Dan33l** [wp-cli/core-command#79]
I use WP-CLI 1.5.1 to configure WordPress 4.9.8.

Install the wordpress is done with command like : 
`wp core install --url=https://wp.foo.org} --title="the answer is not 42" --admin_user="admin" --admin_password="secretpassword" --admin_email=contact@foo.org --skip-email`

Update the title, after the installation is done, looks to be with command like : 
`wp option update blogname 'the answer is 42, but the question was wrong'`

`title` and `blogname` look to be the same object. If yes, using `blogname` in `wp core install` instead of `title` produces less confusion.

**Comment by swissspidy** [comment]
The option is called blogname for historical reasons. WordPress nowadays tries to use the term site instead of blog, but things like the option name can‘t be changed.

When using WP-CLI to install core like in your example, title makes way more sense to me than blogname.

I don‘t think we should change title there, so I guess we‘re stuck with that difference there...

**Comment by danielbachhuber** [comment]
I agree — this isn't something worth changing at this point. Knowing these differences is expected knowledge for WP-CLI.
